# Generated by Django 4.1.5 on 2023-02-05 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Content', models.TextField()),
                ('is_published', models.BooleanField()),
                ('publish_date', models.DateField()),
            ],
        ),
    ]
