# Generated by Django 4.1.6 on 2023-02-08 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='game',
            new_name='blog',
        ),
    ]
