# Generated by Django 4.1.5 on 2023-02-06 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='startA',
            field=models.CharField(blank=True, max_length=1204, null=True),
        ),
    ]
