# Generated by Django 4.1.6 on 2023-02-07 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='conttent',
            new_name='content',
        ),
    ]
