# Generated by Django 4.1.6 on 2023-02-09 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_comenit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='comenit',
            name='name',
        ),
    ]
