# Generated by Django 4.1.5 on 2023-02-07 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_post_starta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='startA',
        ),
    ]
