# Generated by Django 4.1.5 on 2023-02-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_post_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_published',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='publish_date',
            field=models.DateTimeField(),
        ),
    ]
