# Generated by Django 4.1.5 on 2023-02-08 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post_P',
            new_name='post_rev',
        ),
    ]
