# Generated by Django 4.1.5 on 2023-02-05 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='Content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='Title',
            new_name='title',
        ),
    ]
