# Generated by Django 4.1.6 on 2023-02-06 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Title',
            field=models.CharField(max_length=100),
        ),
    ]
